### ISSUE TITLE
Resulting zip has missing executable permission

### ISSUE THREAD

**Issue by abulka** [vimtor/action-zip#21]
Seems that executables get stripped of their +x flag when using this action. Permissions should be preserved.

Original files:
```
# ls -l build/linux/x64/release/bundle/
total 36
-rwxr-xr-x 1 root root 24480 Oct 30 04:51 ai_images_manager     <---- executable
drwxr-xr-x 3 root root  4096 Oct 30 04:51 data
drwxr-xr-x 3 root root  4096 Oct 30 04:51 images-icons
drwxr-xr-x 2 root root  4096 Oct 30 04:51 lib
```

```yaml
  - name: Archive Release 
    uses: vimtor/action-zip@v1
    with:
      files: build/linux/x64/release/bundle/ README.md
      dest: MyApp-${{github.ref_name}}-linux.zip
```
When I unzip the resulting zip, the executable is missing the `x` permission and cannot be executed. 

```
-rw-r--r-- 1 root root    2850 Oct 30 04:51 README.md
-rw-r--r-- 1 root root   24480 Oct 30 04:51 ai_images_manager   <--- missing +x
drwxr-xr-x 3 root root    4096 Oct 30 04:51 data
drwxr-xr-x 2 root root    4096 Oct 30 04:51 lib
```

By contrast, regular linux `zip` and e.g. a competing zip action https://github.com/TheDoctor0/zip-release preserve the `+x` permission.
