### ISSUE TITLE
Add a directory: input

### ISSUE THREAD

**Issue by dehilsterlexis** [vimtor/action-zip#22]
I would like to be able to put all the zipped files into a parent folder. It would be something like:

```
- uses: vimtor/action-zip@v1
  with:
    files: dist/ manifest.json
    recursive: false
    directory: analyzers
    dest: result.zip
```
This would produce a zipped folder named "analyzers" with all the files underneath.
