### ISSUE TITLE
Incorrectly includes folder

### ISSUE THREAD

**Issue by dmrickey** [vimtor/action-zip#25]
Readme says 
![image](https://user-images.githubusercontent.com/3664822/229142545-1e5a1c4e-98ec-4d96-a1ad-03476a1d4dfd.png)

This is in my action
```
    - uses: vimtor/action-zip@v1
      with:
        files: dist/
        recursive: false
        dest: output.zip
```

But the files in my `dist` folder weren't added to the root. The folder as is was included in the zip
