### ISSUE TITLE
nested zip files

### ISSUE THREAD

**Issue by lauramariel** [vimtor/action-zip#26]
I'm doing something like this but when I download the artifact it contains seedPC.zip again. What am I missing?

seedPC.zip -> unzip -> seedPC.zip -> unzip -> contents of lab directory

```
      - name: Easy Zip Files
        # You may pin to the exact commit or the version.
        # uses: vimtor/action-zip@5f1c4aa587ea41db1110df6a99981dbe19cee310
        uses: vimtor/action-zip@v1
        with:
          # Files or directories to zip
          files: assets/lab
          # Name of output zip file
          dest: seedPC.zip
          # Whether to add subdirectories to simply zip all files to the root
          recursive: true
     
      - name: Upload SeedPC
        uses: actions/upload-artifact@v1
        with:
          name: seedPC
          path: ${{ github.workspace }}/seedPC.zip
```
