### ISSUE TITLE
Folders are not included directly

### ISSUE THREAD

**Issue by kvark** [vimtor/action-zip#8]
Looks like the contents of the folders are included instead of the folders themselves.
https://github.com/kvark/vange-rs/runs/3389417025?check_suite_focus=true

```
Run papeloto/action-zip@v1
  with:
    files: res config road model car level convert
    dest: vangers-macos-latest.zip
    recursive: true
Ready to zip "res config road model car level convert" into vangers-macos-latest.zip
  - res
  - config
  - road
  - model
  - car
  - level
  - convert

Zipped file vangers-macos-latest.zip successfully
```

Downloading the file and unzipping it shows me:
```
graphics35334:vangers-macos-latest dmalyshau$ ls -l
total 60632
-rw-rw-r--@  1 dmalyshau  staff  7109656 21 Aug  2021 car
-rw-rw-r--@  1 dmalyshau  staff  1751632 21 Aug  2021 convert
-rw-rw-r--@  1 dmalyshau  staff  7396816 21 Aug  2021 level
-rw-rw-r--@  1 dmalyshau  staff  7016240 21 Aug  2021 model
-rw-rw-r--@  1 dmalyshau  staff  7759656 21 Aug  2021 road
-rw-rw-r--@  1 dmalyshau  staff     1571 21 Aug  2021 settings.template.ron
drwxrwxr-x@ 20 dmalyshau  staff      640 21 Aug  2021 shader
```

So, instead of `res` folder, the archive contains the `shader` folder, which is inside. Same for `config`, which is absent, but the file from it is here.
